### ISSUE TITLE
小程序报错

### ISSUE THREAD

**Issue by longdan** [zz570557024/vue-mpvue-ChatRobot#1]
VM1962:formatted:311 thirdScriptError 
 sdk uncaught third Error 
 Vue is not defined 
 ReferenceError: Vue is not defined
    at Object.269 (http://127.0.0.1:40457/appservice/static/js/pages/stockList/main.js:122:1)
    at __webpack_require__ (http://127.0.0.1:40457/appservice/static/js/manifest.js:55:30)
    at Object.247 (http://127.0.0.1:40457/appservice/static/js/pages/stockList/main.js:7:141)
    at __webpack_require__ (http://127.0.0.1:40457/appservice/static/js/manifest.js:55:30)
    at Object.253 (http://127.0.0.1:40457/appservice/static/js/pages/stockList/main.js:64:65)
    at __webpack_require__ (http://127.0.0.1:40457/appservice/static/js/manifest.js:55:30)
    at Object.webpackJsonpCallback [as webpackJsonp] (http://127.0.0.1:40457/appservice/static/js/manifest.js:26:23)
    at http://127.0.0.1:40457/appservice/static/js/pages/stockList/main.js:1:287
    at require (http://127.0.0.1:40457/appservice/__dev__/WAService.js:19:31596)
    at http://127.0.0.1:40457/appservice/__dev__/WAService.js:19:31310

**Comment by longdan** [comment]
VM1962:formatted:311 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'querySelector' of undefined 
 TypeError: Cannot read property 'querySelector' of undefined

**Comment by longdan** [comment]
thirdScriptError 
 sdk uncaught third Error 
 module "static/ec-canvas/ec-canvas.js" is not defined 
 Error: module "static/ec-canvas/ec-canvas.js" is not defined

**Comment by zz570557024** [comment]
稍等，我本周内会把对移动端和小程序兼容性更好的版本发布出来。尽可能做到没有报错。

**Comment by longdan** [comment]
期待ing

**Comment by zz570557024** [comment]
代码已更新，请阅读文档。
